# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jeferson Amorim | Programador sem fronteira
author: programadorsemfronteira
email: programadorsemfronteira@gmail.com
header: Programador sem fronteira
description: >- # this means to ignore newlines until "baseurl:"
  Como aprender a programar pode ser um desafio, Me siga que eu vou te ajudar
  nesse processo do zero. Programar mudou a minha vida e tenho certeza que pode
  mudar a sua. Procurando uma oportunidade? Ela pode estar aqu!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: prgsemfronteira
github_username:  amorimjj
linkedin_username: jeferson-amorim
facebook_username: programadorsemfronteira
instagram_username: programadorsemfronteira
youtube_channel: UCpiUWQJ-qcHqgwd3PsmgCMQ
youtube_username: programadorsemfronteira
npm_username: amorimjj

google_analytics: G-Q0F5NMBBHX

excerpt_separator: <!--more-->

defaults:
  - scope:
      type: tags
    values:
      layout: posts-tag-list

tags_config:
  - name: frontend
    title: Tudo sobre frontend que já foi revelado aqui
    description: >- # this means to ignore newlines until "baseurl:"
      Aprender a programar pode ser um desafio. Me siga que eu vou te ajudar
      nesse processo. Programar mudou a minha vida e tenho certeza que pode

  - name: backend
    title: Tudo sobre backend que já foi revelado aqui
    description: >- # this means to ignore newlines until "baseurl:"
      Aprender a programar pode ser um desafio. Me siga que eu vou te ajudar
      nesse processo. Programar mudou a minha vida e tenho certeza que pode

  - name: fullstack
    title: Tudo sobre backend que já foi revelado aqui
    description: >- # this means to ignore newlines until "baseurl:"
      Aprender a programar pode ser um desafio. Me siga que eu vou te ajudar
      nesse processo. Programar mudou a minha vida e tenho certeza que pode

where_am_i:
  image: headquarters.jpg
  location: José Menino, Santos, SP, Brasil
  tags:
    - trabalho remoto

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
